query listProjet(
  $appId: ID = "iea"
  $lang: String = "en"
  $options: ListInput = {}
) {
  listProjects(appId: $appId, lang: $lang, options: $options) {
    items {
      color
      date
      description
      featured
      subtitle
      name
      url
    }
    total
  }
}
