query getEvent($appId: ID = "iea", $itemId: ID = "", $lang: String = "") {
  getEvent(itemId: $itemId, appId: $appId, lang: $lang) {
    appId
    availableSlots
    bookingState
    category
    createdBy
    dateText
    description
    details
    id
    image {
      alt
      caption
      backgroundColor
      copyright
      license
      licenseUrl
      url
    }
    name
    place {
      address
      id
      name
      url
    }
    start
    slots {
      email
      firstname
      institution
      lang
      lastname
    }
    state
    stop
    subtitle
    summary
    program
    totalSlots
    type
    url
  }
}
