query getProject($appId: ID = "", $lang: String = "", $itemId: String = "") {
  getProject(appId: $appId, itemId: $itemId, lang: $lang) {
    color
    date
    description
    featured
    subtitle
    title
    url
  }
}
