query listEvents(
  $filter: EventFilterInput
  $pagination: PaginationInput
  $sort: SortInput
) {
  events(filter: $filter, pagination: $pagination, sort: $sort) {
    name
    description
    start
    stop
    location {
      name
      city
      country
    }
    speakers {
      firstname
      lastname
    }
  }
}

query getEvent($name: String!) {
  event(name: $name) {
    name
    description
    start
    stop
    location {
      name
      city
      country
    }
    speakers {
      firstname
      lastname
    }
    tags {
      name
    }
  }
}
