query listPeople(
  $filters: ListInput = {}
  $appId: ID = "iea"
  $lang: String = "en"
) {
  listPeople(appId: $appId, filters: $filters, lang: $lang) {
    total
    items {
      id
      firstname
      lastname
      image
      socials {
        website
        wikipedia
        orcid
        linkedin
        twitter
        instagram
        scholar
        researchgate
        mendeley
        idRef
      }
      biography
    }
  }
}
