backend:
  name: github
  repo: IEA-Paris/seed
  branch: main
  base_url: https://85o05b11ri.execute-api.eu-west-2.amazonaws.com/
  auth_endpoint: "/dev/auth"
  cms_label_prefix: "IEA-Paris/"
publish_mode: editorial_workflow
media_folder: "public"
public_folder: "/"
site_url: https://paris-iea.fr
logo_url: /icon.png
show_preview_links: false
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
i18n:
  structure: multiple_folders
  locales: [en, fr]
  default_locale: en
collections:
  - name: "editorial"
    label: "Editorial content" # Used in the UI
    i18n: true
    slug: "{{title}}"
    folder: "content/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: id, name: id, widget: string, i18n: duplicate }
      - { label: Body, name: body, widget: markdown, i18n: true }
