backend:
  name: github
  repo: IEA-Paris/seed
  branch: main
  base_url: https://85o05b11ri.execute-api.eu-west-2.amazonaws.com/
  auth_endpoint: "/dev/auth"
  cms_label_prefix: "IEA-Paris/"
publish_mode: editorial_workflow
media_folder: "public"
public_folder: "/"
site_url: https://paris-iea.fr
logo_url: /icon.png
show_preview_links: false
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
i18n:
  structure: multiple_folders
  locales: [en, fr]
  default_locale: en
collections:
  - name: "pages"
    label: "Editorial content" # Used in the UI
    i18n: true
    filter: {field: 'page', value: 'home'}
    folder: "content/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown, i18n: true }
  - name: "actions"
    label: "Actions (ads)" # Used in the UI
    i18n: true
    folder: "content/actions" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown, i18n: true }
      - { label: Picture, name: picture, widget: image, i18n: true }
      - { label: Link, name: link, widget: string, i18n: true }

  - name: "carousel"
    label: "Carousel" # Used in the UI
    i18n: true
    folder: "content/carousel" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown, i18n: true }
      - { label: Picture, name: picture, widget: image, i18n: true }
      - { label: Link, name: link, widget: string, i18n: true }
      - { label: Date, name: date, widget: datetime, i18n: true }

  - name: "partners"
    label: "Partners" # Used in the UI
    folder: "content/partners" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    i18n: true
    fields:
      - { label: title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown }
      - {
          label: Picture,
          name: picture,
          widget: image,
          i18n: true,
          media_library:
            { allow_multiple: false, media_folder: "images/partners" },
        }
      - { label: URL, name: url, widget: string, i18n: true }
      - { label: Color, name: color, widget: color, i18n: true }
  - name: "members"
    label: "Members" # Used in the UI
    folder: "content/members" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    i18n: true
    fields:
      - { label: title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown }
      - {
          label: Picture,
          name: picture,
          widget: image,
          i18n: true,
          media_library:
            { allow_multiple: false, media_folder: "images/members" },
        }
      - { label: URL, name: url, widget: string, i18n: true }
      - { label: Color, name: color, widget: color, i18n: true }
  - name: "programs"
    label: "Programs" # Used in the UI
    folder: "content/programs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    i18n: true
    fields:
      - { label: title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown }
      - {
          label: Picture,
          name: picture,
          widget: image,
          i18n: true,
          media_library:
            { allow_multiple: false, media_folder: "images/programs" },
        }
      - { label: URL, name: url, widget: string, i18n: true }
      - { label: Color, name: color, widget: color, i18n: true }
  - name: "fellowships"
    label: "Fellowships" # Used in the UI
    folder: "content/fellowships" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    i18n: true
    fields:
      - { label: title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown }
      - {
          label: Picture,
          name: picture,
          widget: image,
          i18n: true,
          media_library:
            { allow_multiple: false, media_folder: "images/fellowships" },
        }
      - { label: URL, name: url, widget: string, i18n: true }
      - { label: Color, name: color, widget: color, i18n: true }
  - name: "reports"
    label: "Reports" # Used in the UI
    folder: "content/reports" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    i18n: true
    fields:
      - { label: title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown }
      - {
          label: Picture,
          name: picture,
          widget: image,
          i18n: true,
          media_library:
            { allow_multiple: false, media_folder: "images/reports" },
        }
      - { label: URL, name: url, widget: string, i18n: true }
      - { label: Color, name: color, widget: color, i18n: true }
  - name: "sab"
    label: "Scientific Advisory Board" # Used in the UI
    folder: "content/sab" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    i18n: true
    fields:
      - { label: title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown }
      - {
          label: Picture,
          name: picture,
          widget: image,
          i18n: true,
          media_library: { allow_multiple: false, media_folder: "images/sab" },
        }
      - { label: URL, name: url, widget: string, i18n: true }
      - { label: Color, name: color, widget: color, i18n: true }
