backend:
  name: github
  repo: IEA-Paris/seed
  branch: main
  base_url: https://85o05b11ri.execute-api.eu-west-2.amazonaws.com/
  auth_endpoint: "/dev/auth"
  cms_label_prefix: "IEA-Paris/"
publish_mode: editorial_workflow
media_folder: "public"
public_folder: "/"
site_url: https://paris-iea.fr
logo_url: /icon.png
show_preview_links: false
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
i18n:
  structure: multiple_folders
  locales: [en, fr]
  default_locale: en
collections:
  - name: "pages"
    label: "Editorial content" # Used in the UI
    i18n: true
    folder: "content/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown, i18n: true }
  - name: "actions"
    label: "Actions (ads)" # Used in the UI
    i18n: true
    folder: "content/actions" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown, i18n: true }
      - { label: Picture, name: picture, widget: image, i18n: true }
      - { label: Link, name: link, widget: string, i18n: true }

  - name: "carousel"
    label: "Carousel" # Used in the UI
    i18n: true
    folder: "content/carousel" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown, i18n: true }
      - { label: Picture, name: picture, widget: image, i18n: true }
      - { label: Link, name: link, widget: string, i18n: true }
      - { label: Date, name: date, widget: datetime, i18n: true }

  - name: "partners"
    label: "Partners" # Used in the UI
    folder: "content/partners" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    i18n: true
    fields:
      - { label: title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown }
      - {
          label: Picture,
          name: picture,
          widget: image,
          i18n: true,
          media_library:
            { allow_multiple: false, media_folder: "images/partners" },
        }
      - { label: URL, name: url, widget: string, i18n: true }
      - { label: Color, name: color, widget: color, i18n: true }
  - name: "members"
    label: "Members" # Used in the UI
    folder: "content/members" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    i18n: true
    fields:
      - { label: title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown }
      - {
          label: Picture,
          name: picture,
          widget: image,
          i18n: true,
          media_library:
            { allow_multiple: false, media_folder: "images/members" },
        }
      - { label: URL, name: url, widget: string, i18n: true }
      - { label: Color, name: color, widget: color, i18n: true }
  - name: "programs"
    label: "Programs" # Used in the UI
    folder: "content/programs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    i18n: true
    fields:
      - { label: title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown }
      - {
          label: Picture,
          name: picture,
          widget: image,
          i18n: true,
          media_library:
            { allow_multiple: false, media_folder: "images/programs" },
        }
      - { label: URL, name: url, widget: string, i18n: true }
      - { label: Color, name: color, widget: color, i18n: true }
  - name: "fellowships"
    label: "Fellowships" # Used in the UI
    folder: "content/fellowship" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    i18n: true
    fields:
      - { label: title, name: title, widget: string, i18n: true }
      - {
          label: Body,
          name: body,
          widget: markdown,
          hint: "fellowship description",
          i18n: true,
        }
      - {
          label: "Short description",
          name: "shortDescription",
          widget: "text",
          hint: "Shown in the list item view",
          i18n: true,
        }

      - {
          label: Picture,
          name: picture,
          widget: image,
          i18n: true,
          required: false,
          media_library:
            { allow_multiple: false, media_folder: "images/fellowships" },
        }
      - {
          label: Link,
          name: link,
          widget: string,
          required: false,
          i18n: true,
          hint: "link to an external page if it is not a fellowship page hosted by us",
        }
      - {
          label: Action,
          name: action,
          required: false,
          widget: string,
          i18n: true,
          hint: "URL of the application or action page",
        }
      - {
          label: Contact,
          hint: "Email or URL of a contact page",
          name: contact,
          widget: string,
          i18n: true,
        }
      - {
          label: "Publication date",
          name: publicationDate,
          widget: datetime,
          i18n: true,
        }
      - { label: "Opening date", name: opening, widget: datetime, i18n: true }
      - { label: "Closing date", name: closing, widget: datetime, i18n: true }
      - {
          label: Details,
          name: "details",
          widget: "object",
          summary: "{{fields.label}}",
          fields:
            [
              {
                hint: "en groupe, durée courte ou longue, etc.",
                label: "Type",
                name: "type",
                widget: "text",
                i18n: true,
              },
              {
                hint: " Dates et détails temporels",
                label: "Funding period",
                name: "fundingPeriod",
                widget: "text",
                i18n: true,
              },
              {
                hint: " profile, CV, disciplines, expérience, origine",
                label: "Profile",
                name: "profile",
                widget: "text",
                i18n: true,
              },
              {
                hint: " obligations type conférences, publications, attendance -seminaire, bureau",
                label: "Tasks",
                name: "tasks",
                widget: "text",
                i18n: true,
              },
              {
                hint: " texte court sur l’emplacement IEA avec lien vers page dédiée",
                label: "Location",
                name: "location",
                widget: "text",
                i18n: true,
              },
              {
                hint: " texte sur la bourse, minimal",
                label: "Funding",
                name: "funding",
                widget: "text",
                i18n: true,
              },
              {
                hint: " texte court sur logement avec lien page dédiée CIUP",
                label: "Housing",
                name: "housing",
                widget: "text",
                i18n: true,
              },
              {
                hint: " texte court repas, forfait, annulations…",
                label: "Meals",
                name: "meals",
                widget: "text",
                i18n: true,
              },
              {
                hint: " liste des éléments à fournir",
                label: "Application Materials",
                name: "applicationMaterials",
                widget: "text",
                i18n: true,
              },
              {
                hint: " Dates, arbitrages, etc.",
                label: "Selection process",
                name: "selectionProcess",
                widget: "text",
                i18n: true,
              },
              {
                hint: " cf les moyens de la recherche",
                label: "Research support",
                name: "researchSupport",
                widget: "text",
                i18n: true,
              },
            ],
        }

  - name: "reports"
    label: "Reports" # Used in the UI
    folder: "content/reports" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    i18n: true
    fields:
      - { label: title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown }
      - {
          label: Picture,
          name: picture,
          widget: image,
          i18n: true,
          media_library:
            { allow_multiple: false, media_folder: "images/reports" },
        }
      - { label: URL, name: url, widget: string, i18n: true }
      - { label: Color, name: color, widget: color, i18n: true }
  - name: "sab"
    label: "Scientific Advisory Board" # Used in the UI
    folder: "content/sab" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    i18n: true
    fields:
      - { label: title, name: title, widget: string, i18n: true }
      - { label: Body, name: body, widget: markdown }
      - {
          label: Picture,
          name: picture,
          widget: image,
          i18n: true,
          media_library: { allow_multiple: false, media_folder: "images/sab" },
        }
      - { label: URL, name: url, widget: string, i18n: true }
      - { label: Color, name: color, widget: color, i18n: true }
